# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: gen_user
output: ../../gen/user/user_server.go
generate:
  gin-server: true
output-options:
  # to make sure that all types are generated
  skip-prune: true
  include-tags:
    - user