# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: gen_store
output: ../../gen/store/store_models.go
generate:
  models: true
output-options:
  # to make sure that all types are generated
  skip-prune: true
  include-tags:
    - store
  exclude-schemas:
    - Pet
    - Category
    - Tag
    - Customer
    - Address
    - User
    - ApiResponse