pet-server:
  generate:
    gin-server: true
    embedded-spec: true
  package: pet
  output: ../server/pet/pet_server.go
  output-options:
    # skip-prune: true
    include-tags:
      - pet
  import-mapping:
    pet.yaml: github.com/ikhsanurasidb/oapi-codegen-multiple-packages-example/internal/dto/pet
  
pet-models:
  generate:
    models: true
    embedded-spec: true
  package: pet
  output: ../dto/pet/pet_dto.go
  output-options:
    skip-prune: true
    include-tags:
      - pet
    exclude-schemas:
      - Customer
      - Address
      - Order
      - User
      - UserArray

store-server:
  generate:
    embedded-spec: true
    gin-server: true
  package: store
  output: ../server/store/store_server.go
  output-options:
    skip-prune: true
    include-tags:
      - store
  import-mapping:
    store.yaml: github.com/ikhsanurasidb/oapi-codegen-multiple-packages-example/internal/dto/store

store-models:
  generate:
    models: true
    embedded-spec: true
  package: store
  output: ../dto/store/store_dto.go
  output-options:
    skip-prune: true
    include-tags:
      - store
    exclude-schemas:
      - Pet
      - Category
      - Tag
      - Customer
      - Address
      - User
      - UserArray

user-server:
  generate:
    embedded-spec: true
    gin-server: true
  package: user
  output: ../server/user/user_server.go
  output-options:
    skip-prune: true
    include-tags:
      - user
  import-mapping:
    user.yaml: github.com/ikhsanurasidb/oapi-codegen-multiple-packages-example/internal/dto/user

user-models:
  generate:
    models: true
    embedded-spec: true
  package: user
  output: ../dto/user/user_dto.go
  output-options:
    skip-prune: true
    include-tags:
      - user
    exclude-schemas:
      - Pet
      - Category
      - Tag
      - Customer
      - Address
      - Order
      - ApiResponse