# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: pet
output: ../gen/models.gen.go
generate:
  models: true
output-options:
  # to make sure that all types are generated
  skip-prune: true
  include-tags:
    - pet
  exclude-schemas:
    - Customer
    - Address
    - Order
    - User
    - UserArray