pet-server:
  generate:
      gin-server: true
  package: gen_pet
  output: ../generated/pet/pet_server.go
  output-options:
    skip-prune: true
    include-tags:
      - pet

pet-models:
  generate:
      models: true
  package: gen_pet
  output: ../generated/pet/pet_models.go
  output-options:
    include-tags:
      - pet
    exclude-schemas:
      - Customer
      - Address
      - Order
      - User
      - UserArray

store-server:
  generate:
      gin-server: true
  package: gen_store
  output: ../generated/store/store_server.go
  output-options:
    skip-prune: true
    include-tags:
      - store

store-models:
  generate:
      models: true
  package: gen_store
  output: ../generated/store/store_models.go
  output-options:
    skip-prune: true
    include-tags:
      - store
    exclude-schemas:
      - Pet
      - Category
      - Tag
      - Customer
      - Address
      - User
      - UserArray

user-server:
  generate:
      gin-server: true
  package: gen_user
  output: ../generated/user/user_server.go
  output-options:
    skip-prune: true
    include-tags:
      - user

user-models:
  generate:
      models: true
  package: gen_user
  output: ../generated/user/user_models.go
  output-options:
    skip-prune: true
    include-tags:
      - user
    exclude-schemas:
      - Pet
      - Category
      - Tag
      - Customer
      - Address
      - Order
      - ApiResponse