# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: gen_pet
output: ../../gen/pet/pet_models.go
generate:
  models: true
output-options:
  # to make sure that all types are generated
  skip-prune: true
  include-tags:
    - pet
  exclude-schemas:
    - Customer
    - Address
    - Order
    - User
    - UserArray